name: Publish to DockerHub

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python install -r requirements.txt
        python install pytest
    - name: Run test
      run: python pytest-v

  Deploy:
    - name: Deploy to Docker Hub
      needs: Build
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        docker build -t pythonimage .
        docker tag pythoncustom marco501/pythoncustom
        docker push marco501/pythoncustom
